#!/bin/sh     
ssh -tt ubuntu@ip-172-31-37-49 <<EOF
cd algoacademy
pwd
git pull origin master
npm install
cd /client
npm install
npm run-script build
cd ..
sudo systemctl restart nginx
sudo pm2 restart all
exit
EOF
