#!/bin/sh     
curl https://gist.githubusercontent.com/cornflourblue/f0abd30f47d96d6ff127fe8a9e5bbd9f/raw/e3047c9dc3ce8b796e7354c92d2c47ce61981d2f/setup-nodejs-mongodb-production-server-on-ubuntu-1804.sh | sudo bash
cd algoacademy
pwd
git pull origin master
npm install
cd /client
npm install
npm run-script build
cd ..
sudo systemctl restart nginx
sudo pm2 restart all
