#!/bin/sh     
ssh ubuntu@ec2-18-218-101-133.us-east-2.compute.amazonaws.com <<EOF
git pull
npm install
cd client/
npm install
npm run-script build
cd ../
sudo systemctl restart nginx
sudo pm2 restart all
exit      
EOF
